language: java
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
git:
  depth: false

env:
  GRADLE_OPTS: >-
    -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
  GRADLE_CMD_OPTS: >-
    --console=plain
    --continue
    --no-daemon
    --parallel

install: "./gradlew $GRADLE_CMD_OPTS assemble compileTest"
script:  "./gradlew $GRADLE_CMD_OPTS build"
