# Bungee Chat configuration by shawn_ian (v10)
#
# Information about the placeholders can be found here:
# https://github.com/AuraDevelopmentTeam/BungeeChatWiki/wiki/Placeholders
# You can report bugs or request features here:
# https://github.com/AuraDevelopmentTeam/BungeeChat2/issues
# You can contact a developer by joining our Discord server:
# https://discord.me/bungeechat
#
# You can change the settings and messages/formats of the plugin in this file.
# Please do not change the 'Version' value, or else the plugin might not work.

Version: 10.0

Settings:
  Modules:
  #-----------------------#
    Alert:
      enabled: true
      aliases:
        - broadcast
        - bc
        - balert
        - bbc
  #-----------------------#
    AntiAdvertising:
      enabled: true
      whitelisted:
        - www.google.com
  #-----------------------#
    AntiDuplication:
      enabled: true
      checkPastMessages: 5
  #-----------------------#
    AntiSwear:
      enabled: true
      freeMatching: false
      leetSpeak: false
      ignoreSpaces: false
      ignoreDuplicateLetters: false
      words:
        - fuck
        - kut
        - tyfus
      replacement: "****"
  #-----------------------#
    AutoBroadcast:
      enabled: false
      random: false
      interval: 20
      messages:
       - "Message 1"
       - "Message 2\nWith newline!"
  #-----------------------#
    ChatLock:
      enabled: true
      emptyLinesOnClear: 20
      aliases:
        - lockchat
  #-----------------------#
    ChatLogging:
      enabled: true
      privateMessages: true
      console: true
      file: true
      logFile: "logs/%year%-%month%-%day%-chat.log"
  #-----------------------#
    ClearChat:
      enabled: true
      emptyLines: 20
      aliases:
        - cc
        - chatclear
  #-----------------------#
    GlobalChat:
      enabled: true
      passToClientServer: false
      aliases:
        - g
      default: false
      symbol:
        enabled: false
        symbol: "!"
      serverList:
        enabled: false
        list:
          - Hub1
          - Hub2
          - Hub3
  #-----------------------#
    HelpOp:
      enabled: true
      aliases:
        - ahelp
        - helpme
  #-----------------------#
    Ignoring:
      enabled: true
      aliases: []
  #-----------------------#
    JoinMessage:
      enabled: true
  #-----------------------#
    LeaveMessage:
      enabled: true
  #-----------------------#
    LocalChat:
      enabled: true
      passToClientServer: false
  #-----------------------#
    Messenger:
      enabled: true
      filterMessages: false
      aliases:
        message:
          - msg
          - tell
          - m
          - w
          - whisper
        reply:
          - r
        msgtoggle:
          - mtoggle
  #-----------------------#
    MOTD:
      enabled: true
      message:
        - "This is line 1"
        - "This is line 2"
        - "Placeholders do work in here %name%"
  #-----------------------#
    Muting:
      enabled: true
      aliases:
        mute:
          - silence
        unmute:
          - unsilence
        tempmute:
          - tempsilence
      blockedcommands:
        - message
        - msg
        - whisper
        - m
        - tell
        - t
        - w
        - global
        - g
        - reply
        - r
      ignoreBukkitLocalChat: false
      disableWithOtherMutePlugins: true
  #-----------------------#
    ServerSwitchMessages:
      enabled: true
  #-----------------------#
    Spy:
      enabled: true
      aliases:
        socialspy:
        - sspy
        localspy:
        - lspy
  #-----------------------#
    StaffChat:
      enabled: true
      passToClientServer: false
      aliases:
        - sc
        - s
        - schat
  #-----------------------#
    TabCompletion:
      enabled: true
  #-----------------------#
    Vanish:
      enabled: true
      aliases:
        - bhide
  #-----------------------#
    VersionChecker:
      enabled: true
      checkOnAdminLogin: true
  #-----------------------#
  PermissionsManager:
    defaultPrefix: "&7[Member]"
    defaultSuffix: "&r"

Messages:
# Channel Type Messages
  enableGlobal: "&eYou are now talking in &bglobal chat&e!"
  enableStaffchat: "&eYou are now talking in &astaff chat&e!"
  enableLocal: "&eYou are now talking in &clocal chat&e!"
  globalIsDefault: "&eGlobal chat is already the default chatmode!"
  backToLocal: "&cThe feature linked to the channel you were talking in has been disabled or your permissions have been removed! You are now talking in local chat."
  notInGlobalServer: "&cGlobal Chat is not enabled on this server..."
# Messenger Messages
  messageYourself: "&cYou can not send a private message to yourself..."
  enableMessager: "&eYou have &aenabled&e messaging!"
  disableMessager: "&eYou have &cdisabled&e messaging"
  noReply: "&cYou have nobody to reply."
  replyOffline: "&cThe player you were chatting with is no longer online."
  hasMessagerDisabled: "&c%name% has messaging disabled!"
# Vanish Messages
  enableVanish: "&eYou have &aenabled&e hide mode!"
  disableVanish: "&eYou have &cdisabled&e hide mode!"
# Clear Chat Messages
  clearedLocal: "&e%name% has cleared the chat locally."
  clearedGlobal: "&e%name% has cleared the chat globally."
# Mute Messages
  muted: "&cSorry but you can not talk because you are muted until %muted_until%!"
  unmuteNotMuted: "&cThis player is not muted!"
  muteIsMuted: "This player is already muted!"
  unmute: "&eThe player &c%name% &ehas been unmuted!"
  mute: "&eThe player &c%name% &ehas been muted!"
  tempmute: "&eThe player &c%name% &ehas been muted until %muted_until%"
# Spy Messages
  enableSocialSpy: "&eSocialSpy has been &aenabled&e!"
  disableSocialSpy: "&eSocialSpy has been &cdisabled&e!"
  enableLocalSpy: "&eLocalSpy has been &aenabled&e!"
  disableLocalSpy: "&eLocalSpy has been &cdisabled&e!"
# Error Messages
  notPlayer: "&cYou need to be a player to use this command!"
  playerNotFound: "&cCould not find that player..."
  incorrectUsage: "&cIncorrect usage! Use this command like this: %command%"
  noPermission: "&cYou do not have the permissions to perform this action!"
# Ignore Messages
  hasIgnored: "&c%target_name% is ignoring you..."
  addIgnore: "&eYou have ignored %name%!"
  removeIgnore: "&eYou have un-ignored %name%!"
  alreadyIgnored: "&eYou have are already ignoring this player!"
  ignoreYourself: "&cYou can not ignore yourself!"
  unignoreYourself: "&cYou can not unignore yourself!"
  notIgnored: "&cYou have not ignored this user!"
  ignoreList: "&eOnline users you ignore: &b%message%&e."
  ignoreNobody: "&eYou are ignoring &anobody&e that is online!"
# Filter Messages
  antiAdvertise: "&cPlease do not advertise!"
  antiDuplication: "&cPlease do not spam messages!"
# ChatLock Messages
  enableChatlock: "&eChatting has been disabled!"
  disableChatlock: "&eChatting has been enabled!"
  chatIsLocked: "&cYou may not talk now, the chat has been locked!"
# Prefix/Suffix Messages
  prefixRemoved: "&ePrefix of %name% has been removed!"
  prefixSet: "&ePrefix of %name% has been set to %prefix%."
  suffixRemoved: "&eSuffix of %name% has been removed!"
  suffixSet: "&eSuffix of %name% has been set to %suffix%."
# Update available Message
  updateAvailable: "&aAn update for Bungee Chat is available! Version &6%message%&a. Download it at: &6https://www.spigotmc.org/resources/bungee-chat.12592/&a"

Formats:
  alert: "&9ALERT > &c&l%name%: &r%message%"
  socialSpy: "&9SPY > &e%sender_name% &8-> &e%target_name% &8: &r%message%"
  localSpy: "&9SPY > &8%servername% > &e%name% &8: &r%message%"
  globalChat: "&9GLOBAL > &e%fullname%: %message%"
  messageSender: "&6You &8-> &6%target_name% &8: &r%message%"
  messageTarget: "&6%sender_name% &8-> &6You&8: &r%message%"
  staffChat: "&9STAFF > &e%name%: &r%message%"
  localChat: "%fullname%: %message%"
  joinMessage: "&e%name% has joined the network!"
  leaveMessage: "&e%name% has left the network!"
  helpOp: "&2HELPOP > &e%name%: &r%message%"
  serverSwitch: "&e%name% has moved to the &c%servername% &eserver!"
  chatLoggingConsole: "%channel% > %servername% > %name%: %message%"
  chatLoggingFile: "[%time%]: %channel% > %servername% > %name%(%uuid%): %message%"

AccountDataBase:
  enabled: false
  ip: 0.0.0.0
  port: 3306
  database: BungeeChat
  user: User
  password: Password
  tablePrefix: BungeeChat_
