name: BungeeChat
id: bungeechat
main: dev.aura.bungeechat.BungeeChat
version: ${version}
author: shawn_ian, BrainStone
description: Bungee Chat Plugin
url: https://www.spigotmc.org/threads/bungee-chat.93960
softDepends: [BungeePerms, PowerfulPerms, LuckPerms]