name: Code Checks

on: [push, pull_request]

env:
  GRADLE_OPTS: >-
    -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
  GRADLE_CMD_OPTS: >-
    -PbranchName=${{ github.ref }}
    --console=plain
    --continue
    --no-daemon
    --parallel

jobs:
  spotless:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x64
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Check code formatting
        run: ./gradlew ${{ env.GRADLE_CMD_OPTS }} spotlessCheck
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x64
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build all files
        run: ./gradlew ${{ env.GRADLE_CMD_OPTS }} assemble compileTest
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x64
      - name: Checkout submodules
        run: git submodule update --init --recursive
      # This is to ensure unit tests with MariaDB4j don't fail
      - name: Symlinks for MacOS
        if: ${{ runner.os == 'MacOS' }}
        run: |
          sudo ln -s /usr/lib/libssl.dylib /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
          sudo ln -s /usr/lib/libcrypto.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
      - name: Run all Tests
        id: gradle_tests
        run: ./gradlew ${{ env.GRADLE_CMD_OPTS }} -x spotlessCheck build
      - name: Publish JUnit Test Reports
        if: (success() || failure()) && (github.event_name != 'pull_request')
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ github.token }}
          check_name: 'JUnit Test Report (OS: ${{ matrix.os }})'
      - name: Publish SpotBugs Reports
        if: (success() || failure()) && (github.event_name != 'pull_request')
        uses: jwgmeligmeyling/spotbugs-github-action@v1.2
        with:
          path: '**/build/reports/spotbugs/*.xml'
          token: ${{ github.token }}
          name: 'SpotBugs Report (OS: ${{ matrix.os }})'
