name: Checks

on: [push, pull_request]

env:
  GRADLE_OPTS: >-
    -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
  GRADLE_CMD_OPTS: >-
    -PbranchName=${{ github.ref }}
    --no-daemon
    --console=plain

jobs:
  spotless:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x64
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Check evaluated branch
        run: git describe --all
      - name: Check code formatting
        run: ./gradlew ${{ env.GRADLE_CMD_OPTS }} spotlessCheck
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x64
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build all files
        run: ./gradlew ${{ env.GRADLE_CMD_OPTS }} assemble compileTest
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x64
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Run all Tests
        run: ./gradlew ${{ env.GRADLE_CMD_OPTS }} -x spotlessCheck build
      - name: Publish Test Reports
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
